{{- if .Values.opaauth.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-opaauth
  namespace: {{ .Values.namespace }}
  annotations:
    debug: "enabled-{{ .Values.opaauth.ingress.enabled }}"
    {{- with .Values.opaauth.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.opaauth.ingress.className }}
  {{- if .Values.opaauth.ingress.tls }}
  tls:
    {{- range .Values.opaauth.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.opaauth.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-opaauth
                port:
                  number: {{ $.Values.opaauth.service.port }}
          {{- end }}
    {{- end }}
{{- end }}