apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opa-svc
  labels:
    {{- include "opa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opa.service.type }}
  selector:
    app: {{ .Release.Name }}-opa
  ports:
    - protocol: TCP
      port: {{ .Values.opa.service.port }}
      targetPort: {{ .Values.opa.service.port }}