apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-svc
  labels:
    k8s-app: {{ .Release.Name }}-auth-svc
    {{- include "opaauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opaauth.service.type }}
  ports:
    - name: tcp-{{ .Values.opaauth.service.port }}-{{ .Release.Name }}-auth
      port: {{ .Values.opaauth.service.port }}
      protocol: TCP
      targetPort: {{ .Values.opaauth.service.port }}
      nodePort: {{ .Values.opaauth.service.nodePort }}
  selector:
    k8s-app: {{ .Release.Name }}-auth
  sessionAffinity: None