# Global values
namespace: sandbox-test

# OPAAuth values
opaauth:
  replicaCount: 1
  
  image:
    repository: sajadmirz4ei/opaauth
    tag: v3
    pullPolicy: IfNotPresent
  
  imagePullSecrets:
    - name: docker-pull-secret
  
  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: sandbox-test.bettech.cloud
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ssl-cert
        hosts:
          - sandbox-test.bettech.cloud
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 50Mi
  
  keel:
    policy: force
    trigger: poll
    pollSchedule: "@every 1m"

# OPA values
opa:
  replicaCount: 1
  
  image:
    repository: openpolicyagent/opa
    tag: edge
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8181
  
  logLevel: debug
  
  policies:
    default: |
      package system.authz

      # Helper rules to check conditions
      is_get_users_allowed {
          input.method == "GET"
          input.path == "/api/users"
          input.user != ""
      }

      is_post_users_allowed {
          input.method == "POST"
          input.path == "/api/users"
          input.role == "admin"
      }

      is_post_token_allowed {
          input.method == "POST"
          input.path == "/api/token"
      }

      # Single allow rule that uses the helper rules
      allow = response {
          response := calc_response
      }

      # Calculate the response
      calc_response = true {
          is_get_users_allowed
      }
      calc_response = true {
          is_post_users_allowed
      }
      calc_response = true {
          is_post_token_allowed
      }
      calc_response = false {
          not is_get_users_allowed
          not is_post_users_allowed
          not is_post_token_allowed
      }
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
